// объединение по круд операциям
export const SET_GROUPS = 'SET_GROUPS';
export const SET_FACULTIES = 'SET_FACULTIES';
export const SET_PROFILES = 'SET_PROFILES';
export const SET_DEPARTMENTS = 'SET_DEPARTMENTS';
export const SET_DIRECTIONS = 'SET_DIRECTIONS';
export const SET_DISCIPLINES = 'SET_DISCIPLINES';
export const GET_STUDENT_PROFILE = 'GET_STUDENT_PROFILE';
export const SET_STUDENTS = 'SET_STUDENTS';
export const SET_CURRENT_USER_DATA = 'SET_CURRENT_USER_DATA';
export const SET_SUCCESS_INITIALIZED = 'SET_SUCCESS_INITIALIZED';
export const SET_TEACHERS = 'SET_TEACHERS';
export const SET_STUDENT_ALLOWANCE = 'SET_STUDENT_ALLOWANCE';
export const SET_STUDENT_NO_ALLOWANCE = 'SET_STUDENT_NO_ALLOWANCE';

export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';

export const ADD_DISCIPLINE = 'ADD_DISCIPLINE';
export const ADD_GROUP = 'ADD_GROUP';

export const DELETE_DISCIPLINE = 'DELETE_DISCIPLINE';
export const DELETE_GROUP = 'DELETE_GROUP';

export const UPDATE_DISCIPLINE = 'UPDATE_DISCIPLINE';
export const UPDATE_GROUP = 'UPDATE_GROUP';
